name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}

      - name: Debug environment variables
        run: echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" && echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user_name: "juliabbchv"
          user_email: "julia.bbchv@gmail.com"
